/* Serves the small WebP where the browser supports it and a JPEG where it
   does not, at the size the screen actually needs. The files come out of
   public/img/ — generated by `npm run images`, never the raw camera PNGs.  */

const BASE = import.meta.env.BASE_URL // respects vite.config base: './'

/**
 * name    — 'chocolate' | 'paan' | 'classic' | 'platter'
 * widths  — the generated variants, smallest first
 * sizes   — the CSS width the image is painted at, so the browser can pick
 * eager   — set on the hero shot only; everything else lazy-loads
 */
export default function Photo({
  name,
  widths = [400, 800],
  sizes = '200px',
  alt = '',
  className = '',
  eager = false,
  ...rest
}) {
  const set = (ext) => widths.map((w) => `${BASE}img/${name}-${w}.${ext} ${w}w`).join(', ')
  const fallback = `${BASE}img/${name}-${widths[widths.length - 1]}.jpg`

  return (
    <picture className={className}>
      <source type="image/webp" srcSet={set('webp')} sizes={sizes} />
      <source type="image/jpeg" srcSet={set('jpg')} sizes={sizes} />
      <img
        src={fallback}
        alt={alt}
        loading={eager ? 'eager' : 'lazy'}
        decoding={eager ? 'sync' : 'async'}
        fetchPriority={eager ? 'high' : 'auto'}
        {...rest}
      />
    </picture>
  )
}
